### ISSUE TITLE
PATH is misconfigured in flatpak version

### ISSUE THREAD

**Issue by Daniel-A-Gutierrez** [flathub/com.vscodium.codium#363] opened 2024-09-22 21:44 UTC
https://github.com/rust-lang/rust-analyzer/issues/2873#issuecomment-575815147

as a result rust-analyzer doesn't work.

**Comment by daiyam** [comment] 2024-09-22 23:17
Duplicate of https://github.com/VSCodium/vscodium/issues/2027

**Closed by daiyam** 2024-09-22 23:17 UTC
