### ISSUE TITLE
1.5Gb dependency on org.freedesktop.Sdk

### ISSUE THREAD

**Issue by abitrolly** [flathub/com.vscodium.codium#192] opened 2023-05-24 11:37 UTC
Is it really necessary to depend on `org.freedesktop.Sdk` which takes huge 1.5 GB?

```
$ flatpak remove org.freedesktop.Sdk/x86_64/22.08
...
error: Failed to uninstall org.freedesktop.Sdk: Can't remove org.freedesktop.Sdk/x86_64/22.08, it is needed for: com.vscodium.codium                                /16.5s
```

```
✗ flatpak list --columns name,ref,size
Name                                                    Ref                                                                      Installed size
VSCodium                                                com.vscodium.codium/x86_64/stable                                        326.4 MB
...
Freedesktop SDK                                         org.freedesktop.Sdk/x86_64/22.08                                           1.5 GB
GNOME Application Platform version 43                   org.gnome.Platform/x86_64/43                                             864.0 MB
```

**Comment by noonsleeper** [comment] 2023-07-12 01:36
Hi, in the end, we need the tools that come inside `org.freedesktop.Sdk` for the correct functionality of codium.

But I think the problem is the way in that this package is build, I was thinking for a long time to compile directly the binaries of codium, (but my spare time is limited), I think this could be a better approach to make this build more lightweight.

**Comment by abitrolly** [comment] 2023-07-12 05:14
I don't see any description how the package is built https://github.com/flathub/com.vscodium.codium Is there any?

**Comment by genodeftest** [comment] 2023-07-12 17:57
> I don't see any description how the package is built https://github.com/flathub/com.vscodium.codium Is there any?

The build configuration/scripts are in [com.vscodium.codium.yaml](https://github.com/flathub/com.vscodium.codium/blob/master/com.vscodium.codium.yaml).

**Comment by abitrolly** [comment] 2023-07-13 05:15
So will removing this line help?
```
runtime: org.freedesktop.Sdk
```

**Comment by genodeftest** [comment] 2023-07-13 19:37
Feel free to try it out. I guess it will probably break at some point, either at "compile" time or runtime.

**Comment by noonsleeper** [comment] 2023-08-12 22:18
> So will removing this line help?
> 
> ```
> runtime: org.freedesktop.Sdk
> ```

Sadly, I say that not fix the issue, this need some refactor, but aside that the SDK will be not removed any time soon.

**Comment by noonsleeper** [comment] 2023-08-12 23:59
I'll close this since, we will not remove the SDK, If you have another problem, don't hesitate and open a new issue!

**Closed by noonsleeper** 2023-08-12 23:59 UTC

**Comment by abitrolly** [comment] 2023-08-13 07:58
> this need some refactor

What refactor is needed here?

**Comment by noonsleeper** [comment] 2023-10-18 04:19
For the sdk none, but start to build this from sources instead of unpacking a .deb file

**Comment by larina3315** [comment] 2023-11-27 09:59
> For the sdk none, but start to build this from sources instead of unpacking a .deb file

wouldn't that be the better approach ?
