### ISSUE TITLE
can not open devcontainer

### ISSUE THREAD

**Issue by getreu** [flathub/com.vscodium.codium#28] opened 2020-12-26 08:10 UTC
I would like to open my devcontainers. The following extension is not available

* `ms-vscode-remote.remote-containers`

I also tried 
* ms-azuretools.vscode-docker`

but it can not connect to my host docker daemon
```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-17T00:37:39.556Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.19.0-13-amd64.
```

**Comment by noonsleeper** [comment] 2021-01-09 20:12
> I would like to open my devcontainers. The following extension is not available
> 
>     * `ms-vscode-remote.remote-containers`

For this is I recommend to you could read the license of this extension and ask to openvsx project if they could add to open-vsx.org library more info in this [link](https://github.com/eclipse/openvsx/wiki)
 
for the other problem may be you need to expose `/var/run/docker.sock` to codium's flatpak container, you do this from console or with [flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal)

**Comment by getreu** [comment] 2021-01-11 15:04
Thank you for your help.

> For this is I recommend to you could read the license of this extension and ask to openvsx project if they could add to open-vsx.org library more info in this link

For completeness, here the link: [License - Visual Studio Code Remote Development Extensions](https://code.visualstudio.com/preview-license).  It says: 

> You may not use the software if you do not have a license for Microsoft Visual Studio Code. 

and

> 4. a. Data Collection. The software may collect information about you and your use of the software, and send that to Microsoft. [...] You may opt out of many of these scenarios, but not all, [...!]

For me, both are good reasons to look for an alternative. `ms-azuretools.vscode-docker`  is MIT licensed, although some telemetry is also enabled by default. With

    sudo flatpak override --filesystem=/run/docker.sock com.vscodium.codium

I could connect to the docker demon, but I am still stuck with mounting the workfolder into the container.

**Comment by noonsleeper** [comment] 2021-01-13 01:15
> ```
> sudo flatpak override --filesystem=/run/docker.sock com.vscodium.codium
> ```
> 
> 
> I could connect to the docker demon, but I am still stuck with mounting the workfolder into the container.

The problem is `sudo` you run the flatpak as root user. I think you need to add your user to docker group to be able to run 

```
flatpak override --filesystem=/run/docker.sock com.vscodium.codium
```

only for you user

**Comment by getreu** [comment] 2021-01-13 07:17
`sudo flatpak override` configures the flatpak containers system wide, while `flatpak override --user` does the same for the current user only.
I do not think, this is the reason why I do not get my work folder mounted into the docker container. 
According to [this](https://stackoverflow.com/a/47272481) one should use `mount`. I guess I will have to learn a bit more about Docker and the VScode extension `ms-azuretools.vscode-docker`.

**Comment by noonsleeper** [comment] 2021-02-28 03:34
Hey @getreu Any news about this problem?

**Comment by getreu** [comment] 2021-03-03 10:20
I had not time to investigate more. I am still confident, that it is possible to imitate the `devcontainer`  functionality with the free docker extension. Is someone gets it configured, I am interested to know how.

**Comment by noonsleeper** [comment] 2021-11-19 16:41
Hey @getreu, I will close this ticket since has many month without updates.

**Closed by noonsleeper** 2021-11-19 16:41 UTC

**Comment by getreu** [comment] 2021-11-19 21:50
@noonsleeper yes. It turns out, that there is no need for a plugin to work with devcontainers. To give you an idea you can check out these examples: [tp-note/build-env at master · getreu/tp-note](https://github.com/getreu/tp-note/tree/master/build-env)
