### ISSUE TITLE
Window icon no longer works under KDE Wayland

### ISSUE THREAD

**Issue by RalfJung** [flathub/com.vscodium.codium#149] opened 2022-11-13 17:55 UTC
Until earlier today, vscodium windows had a proper icon in my KDE Wayland Plasma panel taskbar. Today I updated my flatpaks and system packages and did a reboot, and now the icon is broken. The vscodium package got updated to 1.73.1.22314, so I suspect that is where the problem started -- though I don't know how to figure out which version I had installed before.

According to kwin, the `desktopFileName` property of vscodium windows is now set to 'codium-url-handler', which obviously is not correct. (I don't know if before this update, the app has been using Wayland or X11.)

**Comment by RalfJung** [comment] 2022-11-14 07:19
Due to https://github.com/electron/electron/issues/29345, it currently seems better to run electron applications as X11 even when Wayland is available... that wold also work around this issue. But how do I force vscodium to use X11? I tried `flatpak run --socket=x11 --nosocket=wayland com.vscodium.codium` but that did not work.

**Comment by noonsleeper** [comment] 2022-11-14 13:57
Did you try this?

```
sudo flatpak run --nosocket=fallback-x11 --socket=x11 com.vscodium.codium
```

To make the change system-wide?

**Comment by RalfJung** [comment] 2022-11-14 14:18
Just swapping the sockets doesn't help, vscodium somehow still thinks that wayland is supported and tries to use it.

I have now done `flatpak override com.vscodium.codium --user  --nosocket=fallback-x11 --socket=x11`, and edited the application file (KDE has a menu editor for that) to add `--ozone-platform=x11` flags.

Maybe it'd make sense if vscodium (or the underlying ide-support-wrapper) had support for an env var to force the use of X11, so that one can configure this via `flatpak override` without having to add flags to the application invocation.

Of course even better if the icon (and more importantly, XCompose support) were fixed. :D

**Comment by RalfJung** [comment] 2022-11-14 17:31
Yes, and sadly `auto` seems to prefer wayland even if the wayland socket is actually not available. Which arguably is a bug is electron... oh well.

I don't think I can change that locally though? I'd have to rebuilt the package.
Right now I did
```
flatpak override com.vscodium.codium --nosocket=fallback-x11 --socket=x11
flatpak run com.vscodium.codium --ozone-platform=x11
```

**Comment by noonsleeper** [comment] 2022-11-14 21:11
and what is the output of:

```
flatpak override com.vscodium.codium --nosocket=fallback-x11 --nosocket=wayland --socket=x11
flatpak run com.vscodium.codium --verbose
```

**Comment by RalfJung** [comment] 2022-11-15 07:45
```
Warning: 'ozone-platform-hint' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
[18:1115/084525.819429:ERROR:wayland_connection.cc(209)] Failed to connect to Wayland display
[18:1115/084525.819521:ERROR:ozone_platform_wayland.cc(226)] Failed to initialize Wayland platform
[18:1115/084525.819546:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
```

**Comment by noonsleeper** [comment] 2022-11-15 11:19
@RalfJung I tried this on fedora kinoite (X11 session) and works like a charm

```
sudo flatpak override --reset com.vscodium.codium
flatpak --user override --reset com.vscodium.codium
flatpak --user override --nosocket=fallback-x11 --nosocket=wayland --socket=x11 com.vscodium.codium
flatpak run com.vscodium.codium
```

Can you try it?

**Comment by noonsleeper** [comment] 2022-11-15 16:16
Currently, I'm using Flatpak Codium on gnome/wayland

**Comment by RalfJung** [comment] 2022-11-15 16:18
I guess Gnome doesn't have a panel where the window icon could be wrong... not sure if Gnome uses the `desktopFileName` for anything? Doesn't it show window icons in the window switcher, or something like that?

**Comment by noonsleeper** [comment] 2022-11-15 16:37
Can you show me examples of that on KDE?

**Comment by RalfJung** [comment] 2022-11-15 17:17
This is what it looks like in the panel:

![image](https://user-images.githubusercontent.com/330628/201983888-d41081f2-b2be-4222-800e-9b6cb7c8dc21.png)


And it's no surprise, the `desktopFileName` has a nonsense value (`codium-url-handler`). No idea how gnome determines the icon for a window, KDE uses the `desktopFileName`.

**Comment by rimatech987** [comment] 2022-11-16 10:07
Same problem for me as well.
It only works by running this command from the terminal.

```
flatpak run --nosocket=fallback-x11 --socket=x11 com.vscodium.codium --ozone-platform=x11
```

It does not work by running it from the .desktop file. Should I edit it?

O.S. : Fedora 35 Wayland

**Comment by noonsleeper** [comment] 2022-11-16 14:00
@rimatech987 Are you running kde too? Since I'm running fedora37/silverblue/gnome/wayland and the .desktop is working as expected

**Comment by rimatech987** [comment] 2022-11-16 15:20
> @rimatech987 Are you running kde too? Since I'm running fedora37/silverblue/gnome/wayland and the .desktop is working as expected

No, I'm in gnome. 
F35 workstation wayland gnome
I also tried a brand new installation in F36 workstation wayland gnome but nothing, it won't start from the default .desktop shortcut.

**Comment by noonsleeper** [comment] 2022-11-17 21:03
> F35 workstation wayland gnome

Is your terminal spawn on xwayland?

what happens if you run on the terminal

```
flatpak run --socket=fallback-x11 --nosocket=x11 --socket=wayland com.vscodium.codium --ozone-platform=wayland
```


> I also tried a brand new installation in F36 workstation wayland gnome but nothing, it won't start from the default .desktop

Where is located that .desktop file?
What happens if you invoke codium from the menu?

![image](https://user-images.githubusercontent.com/62183384/202559233-f1c16f69-d9fc-4bdf-ae9c-c229f65cce8a.png)

**Comment by noonsleeper** [comment] 2022-11-17 21:09
> This is what it looks like in the panel:
> 
> ![image](https://user-images.githubusercontent.com/330628/201983888-d41081f2-b2be-4222-800e-9b6cb7c8dc21.png)
> 
> And it's no surprise, the `desktopFileName` has a nonsense value (`codium-url-handler`). No idea how gnome determines the icon for a window on wayland, KDE uses the `desktopFileName`.

Do you have any clue about what format kde needs to be the name? Because the ".desktop" files are named like this for compliance
https://github.com/flathub/com.vscodium.codium/blob/c9cfa14dd1c71d5dce6e42bf47e975dbce84f2f0/com.vscodium.codium.yaml#L80-L81

**Comment by RalfJung** [comment] 2022-11-18 12:47
The `desktopFileName` property of the window should be `com.vscodium.codium`.

**Comment by rimatech987** [comment] 2022-11-18 14:12
> what happens if you run on the terminal
> 
> ```
> flatpak run --socket=fallback-x11 --nosocket=x11 --socket=wayland com.vscodium.codium --ozone-platform=wayland
> ```
it doesn't start in this way. 

>  What happens if you invoke codium from the menu?
> ![image](https://user-images.githubusercontent.com/62183384/202559233-f1c16f69-d9fc-4bdf-ae9c-c229f65cce8a.png)

Literally nothing.

**Comment by noonsleeper** [comment] 2022-11-30 19:29
Hey @RalfJung I will apply a bugfix due to a regression with ibus, then the default start when you run will be xwayland again until [this](https://github.com/microsoft/vscode/issues/167757) will be fixed upstream.

**Comment by catdevnull** [comment] 2024-02-23 15:57
still have this issue. F39 Kinoite. if i manually edit `/var/lib/flatpak/exports/share/applications/com.vscodium.codium.desktop` and set `StartupWMClass=codium-url-handler` it works, but of course, that's not a real solution.

**Closed** 2024-06-15 17:11 UTC
